// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vavatech.EFCore.DbServices;

namespace Vavatech.EFCore.DbServices.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20190221124945_TEst")]
    partial class TEst
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vavatech.EFCore.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Pesel");

                    b.Property<decimal>("Salary");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Tim",
                            IsDeleted = false,
                            LastName = "Schroeder",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Carl",
                            IsDeleted = false,
                            LastName = "Pfeffer",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Grady",
                            IsDeleted = true,
                            LastName = "Morar",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Sylvia",
                            IsDeleted = true,
                            LastName = "Turner",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Norman",
                            IsDeleted = true,
                            LastName = "Morar",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Alicia",
                            IsDeleted = true,
                            LastName = "Skiles",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Mildred",
                            IsDeleted = true,
                            LastName = "Maggio",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Carrie",
                            IsDeleted = true,
                            LastName = "Legros",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Agnes",
                            IsDeleted = true,
                            LastName = "McKenzie",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Velma",
                            IsDeleted = true,
                            LastName = "Watsica",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Amos",
                            IsDeleted = false,
                            LastName = "Davis",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Ricky",
                            IsDeleted = true,
                            LastName = "Reinger",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Muriel",
                            IsDeleted = true,
                            LastName = "Connelly",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Curtis",
                            IsDeleted = false,
                            LastName = "Graham",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Marcos",
                            IsDeleted = false,
                            LastName = "Thiel",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Lorenzo",
                            IsDeleted = true,
                            LastName = "Will",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Ricky",
                            IsDeleted = false,
                            LastName = "Crist",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Marty",
                            IsDeleted = true,
                            LastName = "Reichert",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Al",
                            IsDeleted = true,
                            LastName = "Dach",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Agnes",
                            IsDeleted = false,
                            LastName = "Grimes",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Noah",
                            IsDeleted = false,
                            LastName = "Turcotte",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Debbie",
                            IsDeleted = true,
                            LastName = "Hammes",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Andrew",
                            IsDeleted = true,
                            LastName = "Blick",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Sheri",
                            IsDeleted = true,
                            LastName = "Torphy",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Brittany",
                            IsDeleted = true,
                            LastName = "Anderson",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Troy",
                            IsDeleted = true,
                            LastName = "Ledner",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Steve",
                            IsDeleted = false,
                            LastName = "Langworth",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Benny",
                            IsDeleted = true,
                            LastName = "Larkin",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Lola",
                            IsDeleted = true,
                            LastName = "Schaden",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Bryan",
                            IsDeleted = true,
                            LastName = "Strosin",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "Isabel",
                            IsDeleted = true,
                            LastName = "Rempel",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Rickey",
                            IsDeleted = false,
                            LastName = "Turcotte",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "James",
                            IsDeleted = false,
                            LastName = "Rohan",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Luther",
                            IsDeleted = true,
                            LastName = "Boyer",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Bobbie",
                            IsDeleted = true,
                            LastName = "Windler",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "Claude",
                            IsDeleted = true,
                            LastName = "Rohan",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "Kevin",
                            IsDeleted = true,
                            LastName = "Weissnat",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Bert",
                            IsDeleted = true,
                            LastName = "Walker",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Jim",
                            IsDeleted = true,
                            LastName = "Mayer",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Darlene",
                            IsDeleted = true,
                            LastName = "Romaguera",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "Sergio",
                            IsDeleted = true,
                            LastName = "Donnelly",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "Bethany",
                            IsDeleted = true,
                            LastName = "Boyer",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "Thomas",
                            IsDeleted = true,
                            LastName = "O'Keefe",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "Lauren",
                            IsDeleted = false,
                            LastName = "Hintz",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "Jody",
                            IsDeleted = true,
                            LastName = "Trantow",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "Angelica",
                            IsDeleted = true,
                            LastName = "Veum",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "Conrad",
                            IsDeleted = false,
                            LastName = "Hessel",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "Katrina",
                            IsDeleted = true,
                            LastName = "Purdy",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 49,
                            FirstName = "Gerald",
                            IsDeleted = true,
                            LastName = "Herzog",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 50,
                            FirstName = "Lela",
                            IsDeleted = true,
                            LastName = "Beier",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 51,
                            FirstName = "Ruben",
                            IsDeleted = false,
                            LastName = "Wintheiser",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 52,
                            FirstName = "Daniel",
                            IsDeleted = true,
                            LastName = "Mraz",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 53,
                            FirstName = "Sally",
                            IsDeleted = true,
                            LastName = "O'Reilly",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 54,
                            FirstName = "Steven",
                            IsDeleted = true,
                            LastName = "Anderson",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 55,
                            FirstName = "Veronica",
                            IsDeleted = false,
                            LastName = "Sipes",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 56,
                            FirstName = "Shaun",
                            IsDeleted = true,
                            LastName = "Lesch",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 57,
                            FirstName = "Raymond",
                            IsDeleted = true,
                            LastName = "Prohaska",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 58,
                            FirstName = "Carmen",
                            IsDeleted = true,
                            LastName = "Hintz",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 59,
                            FirstName = "Shane",
                            IsDeleted = true,
                            LastName = "Rice",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 60,
                            FirstName = "Nina",
                            IsDeleted = true,
                            LastName = "Haag",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 61,
                            FirstName = "Ted",
                            IsDeleted = true,
                            LastName = "Buckridge",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 62,
                            FirstName = "Curtis",
                            IsDeleted = true,
                            LastName = "Marvin",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 63,
                            FirstName = "Susan",
                            IsDeleted = true,
                            LastName = "Hoppe",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 64,
                            FirstName = "Zachary",
                            IsDeleted = false,
                            LastName = "Douglas",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 65,
                            FirstName = "Roland",
                            IsDeleted = true,
                            LastName = "Schmeler",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 66,
                            FirstName = "Bethany",
                            IsDeleted = true,
                            LastName = "Rolfson",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 67,
                            FirstName = "Oscar",
                            IsDeleted = false,
                            LastName = "Keebler",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 68,
                            FirstName = "Alexis",
                            IsDeleted = true,
                            LastName = "Reynolds",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 69,
                            FirstName = "Beulah",
                            IsDeleted = true,
                            LastName = "Gulgowski",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 70,
                            FirstName = "Grace",
                            IsDeleted = true,
                            LastName = "Beer",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 71,
                            FirstName = "Grady",
                            IsDeleted = true,
                            LastName = "Collier",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 72,
                            FirstName = "Annie",
                            IsDeleted = true,
                            LastName = "Pagac",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 73,
                            FirstName = "Charles",
                            IsDeleted = true,
                            LastName = "Heaney",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 74,
                            FirstName = "Dennis",
                            IsDeleted = true,
                            LastName = "Padberg",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 75,
                            FirstName = "Dorothy",
                            IsDeleted = false,
                            LastName = "Collier",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 76,
                            FirstName = "Isaac",
                            IsDeleted = true,
                            LastName = "Blick",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 77,
                            FirstName = "Johnnie",
                            IsDeleted = true,
                            LastName = "Kerluke",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 78,
                            FirstName = "Marlene",
                            IsDeleted = false,
                            LastName = "Lindgren",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 79,
                            FirstName = "Juana",
                            IsDeleted = true,
                            LastName = "Maggio",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 80,
                            FirstName = "Calvin",
                            IsDeleted = true,
                            LastName = "Rowe",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 81,
                            FirstName = "Lloyd",
                            IsDeleted = true,
                            LastName = "Donnelly",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 82,
                            FirstName = "Jennifer",
                            IsDeleted = true,
                            LastName = "Brown",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 83,
                            FirstName = "Virgil",
                            IsDeleted = true,
                            LastName = "Blanda",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 84,
                            FirstName = "Darren",
                            IsDeleted = true,
                            LastName = "Hamill",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 85,
                            FirstName = "Constance",
                            IsDeleted = true,
                            LastName = "Kling",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 86,
                            FirstName = "Mabel",
                            IsDeleted = true,
                            LastName = "Littel",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 87,
                            FirstName = "Terrance",
                            IsDeleted = true,
                            LastName = "Metz",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 88,
                            FirstName = "Anne",
                            IsDeleted = false,
                            LastName = "Predovic",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 89,
                            FirstName = "Travis",
                            IsDeleted = true,
                            LastName = "Vandervort",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 90,
                            FirstName = "Brandy",
                            IsDeleted = true,
                            LastName = "Huel",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 91,
                            FirstName = "Lloyd",
                            IsDeleted = true,
                            LastName = "Watsica",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 92,
                            FirstName = "Ronald",
                            IsDeleted = true,
                            LastName = "Bradtke",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 93,
                            FirstName = "Dean",
                            IsDeleted = false,
                            LastName = "Wisoky",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 94,
                            FirstName = "Alyssa",
                            IsDeleted = false,
                            LastName = "Bruen",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 95,
                            FirstName = "Jon",
                            IsDeleted = false,
                            LastName = "Boehm",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 96,
                            FirstName = "Rafael",
                            IsDeleted = false,
                            LastName = "Mayer",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 97,
                            FirstName = "Loren",
                            IsDeleted = true,
                            LastName = "Herman",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 98,
                            FirstName = "Lauren",
                            IsDeleted = false,
                            LastName = "Thiel",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 99,
                            FirstName = "Audrey",
                            IsDeleted = true,
                            LastName = "Kuphal",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 100,
                            FirstName = "Ramiro",
                            IsDeleted = true,
                            LastName = "Rodriguez",
                            Salary = 0m
                        });
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<int?>("CustomerId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemId");

                    b.Property<int?>("OrderId");

                    b.Property<int>("Quantity");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.Product", b =>
                {
                    b.HasBaseType("Vavatech.EFCore.Models.Item");

                    b.Property<string>("Color");

                    b.Property<float>("Weight");

                    b.HasDiscriminator().HasValue("Product");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.Service", b =>
                {
                    b.HasBaseType("Vavatech.EFCore.Models.Item");

                    b.Property<TimeSpan>("Duration");

                    b.HasDiscriminator().HasValue("Service");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.Order", b =>
                {
                    b.HasOne("Vavatech.EFCore.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.OrderDetail", b =>
                {
                    b.HasOne("Vavatech.EFCore.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("Vavatech.EFCore.Models.Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
