// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vavatech.EFCore.DbServices;

namespace Vavatech.EFCore.DbServices.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20190221110448_AddPeselToCustomer")]
    partial class AddPeselToCustomer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vavatech.EFCore.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Pesel");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Velma",
                            IsDeleted = true,
                            LastName = "Berge"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Wm",
                            IsDeleted = true,
                            LastName = "Grimes"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Doug",
                            IsDeleted = true,
                            LastName = "Marvin"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Tyler",
                            IsDeleted = false,
                            LastName = "Wisoky"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Brenda",
                            IsDeleted = true,
                            LastName = "Senger"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Stephanie",
                            IsDeleted = true,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Juana",
                            IsDeleted = false,
                            LastName = "Jast"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Judith",
                            IsDeleted = true,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Claude",
                            IsDeleted = true,
                            LastName = "Larkin"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Edgar",
                            IsDeleted = true,
                            LastName = "Borer"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Kathleen",
                            IsDeleted = false,
                            LastName = "Rutherford"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Erick",
                            IsDeleted = true,
                            LastName = "Labadie"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Kristine",
                            IsDeleted = true,
                            LastName = "Crona"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Bernadette",
                            IsDeleted = true,
                            LastName = "Brakus"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Earl",
                            IsDeleted = true,
                            LastName = "Beatty"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Ellis",
                            IsDeleted = false,
                            LastName = "Heidenreich"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Marianne",
                            IsDeleted = true,
                            LastName = "Olson"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Rickey",
                            IsDeleted = true,
                            LastName = "Braun"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Irvin",
                            IsDeleted = true,
                            LastName = "Jerde"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Caroline",
                            IsDeleted = true,
                            LastName = "Hammes"
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Dale",
                            IsDeleted = true,
                            LastName = "Bartoletti"
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Kathleen",
                            IsDeleted = true,
                            LastName = "Nolan"
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Geneva",
                            IsDeleted = true,
                            LastName = "Blanda"
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Loren",
                            IsDeleted = true,
                            LastName = "Conn"
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Shawna",
                            IsDeleted = true,
                            LastName = "Haag"
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Lucia",
                            IsDeleted = true,
                            LastName = "Weimann"
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Andy",
                            IsDeleted = true,
                            LastName = "Grant"
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Donna",
                            IsDeleted = true,
                            LastName = "Frami"
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Christina",
                            IsDeleted = false,
                            LastName = "Osinski"
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Estelle",
                            IsDeleted = true,
                            LastName = "Pfannerstill"
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "Regina",
                            IsDeleted = false,
                            LastName = "Klein"
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Randall",
                            IsDeleted = true,
                            LastName = "Thompson"
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Bradley",
                            IsDeleted = true,
                            LastName = "Treutel"
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Paul",
                            IsDeleted = true,
                            LastName = "Hessel"
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Guillermo",
                            IsDeleted = true,
                            LastName = "Stamm"
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "Gordon",
                            IsDeleted = true,
                            LastName = "Dare"
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "Arlene",
                            IsDeleted = true,
                            LastName = "Nienow"
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Wallace",
                            IsDeleted = true,
                            LastName = "Bartell"
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Rodolfo",
                            IsDeleted = true,
                            LastName = "Greenholt"
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Patrick",
                            IsDeleted = false,
                            LastName = "Walker"
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "Connie",
                            IsDeleted = true,
                            LastName = "Trantow"
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "Bridget",
                            IsDeleted = true,
                            LastName = "Grady"
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "Tammy",
                            IsDeleted = false,
                            LastName = "Bayer"
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "Gertrude",
                            IsDeleted = false,
                            LastName = "Bernhard"
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "Frances",
                            IsDeleted = true,
                            LastName = "Kautzer"
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "Saul",
                            IsDeleted = true,
                            LastName = "Sanford"
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "Constance",
                            IsDeleted = true,
                            LastName = "Brekke"
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "Patti",
                            IsDeleted = true,
                            LastName = "Bailey"
                        },
                        new
                        {
                            Id = 49,
                            FirstName = "Doreen",
                            IsDeleted = true,
                            LastName = "Kling"
                        },
                        new
                        {
                            Id = 50,
                            FirstName = "Latoya",
                            IsDeleted = true,
                            LastName = "Bashirian"
                        },
                        new
                        {
                            Id = 51,
                            FirstName = "Jody",
                            IsDeleted = false,
                            LastName = "Lueilwitz"
                        },
                        new
                        {
                            Id = 52,
                            FirstName = "Doug",
                            IsDeleted = true,
                            LastName = "Carter"
                        },
                        new
                        {
                            Id = 53,
                            FirstName = "Max",
                            IsDeleted = true,
                            LastName = "Gaylord"
                        },
                        new
                        {
                            Id = 54,
                            FirstName = "Elmer",
                            IsDeleted = true,
                            LastName = "Gorczany"
                        },
                        new
                        {
                            Id = 55,
                            FirstName = "Moses",
                            IsDeleted = true,
                            LastName = "Runte"
                        },
                        new
                        {
                            Id = 56,
                            FirstName = "Tommy",
                            IsDeleted = true,
                            LastName = "Rath"
                        },
                        new
                        {
                            Id = 57,
                            FirstName = "Elsa",
                            IsDeleted = true,
                            LastName = "Towne"
                        },
                        new
                        {
                            Id = 58,
                            FirstName = "Pam",
                            IsDeleted = true,
                            LastName = "Pacocha"
                        },
                        new
                        {
                            Id = 59,
                            FirstName = "Ramon",
                            IsDeleted = true,
                            LastName = "Lehner"
                        },
                        new
                        {
                            Id = 60,
                            FirstName = "Beth",
                            IsDeleted = false,
                            LastName = "McDermott"
                        },
                        new
                        {
                            Id = 61,
                            FirstName = "Brenda",
                            IsDeleted = true,
                            LastName = "Blick"
                        },
                        new
                        {
                            Id = 62,
                            FirstName = "Margaret",
                            IsDeleted = true,
                            LastName = "Windler"
                        },
                        new
                        {
                            Id = 63,
                            FirstName = "Christina",
                            IsDeleted = true,
                            LastName = "Lindgren"
                        },
                        new
                        {
                            Id = 64,
                            FirstName = "Rogelio",
                            IsDeleted = true,
                            LastName = "Murray"
                        },
                        new
                        {
                            Id = 65,
                            FirstName = "Cecilia",
                            IsDeleted = true,
                            LastName = "Mayer"
                        },
                        new
                        {
                            Id = 66,
                            FirstName = "Ignacio",
                            IsDeleted = true,
                            LastName = "Auer"
                        },
                        new
                        {
                            Id = 67,
                            FirstName = "Roderick",
                            IsDeleted = true,
                            LastName = "Nader"
                        },
                        new
                        {
                            Id = 68,
                            FirstName = "Julian",
                            IsDeleted = false,
                            LastName = "Lockman"
                        },
                        new
                        {
                            Id = 69,
                            FirstName = "Stella",
                            IsDeleted = true,
                            LastName = "Wehner"
                        },
                        new
                        {
                            Id = 70,
                            FirstName = "Gregg",
                            IsDeleted = true,
                            LastName = "Beer"
                        },
                        new
                        {
                            Id = 71,
                            FirstName = "Kathy",
                            IsDeleted = true,
                            LastName = "Kohler"
                        },
                        new
                        {
                            Id = 72,
                            FirstName = "Kristie",
                            IsDeleted = true,
                            LastName = "Crooks"
                        },
                        new
                        {
                            Id = 73,
                            FirstName = "Joseph",
                            IsDeleted = false,
                            LastName = "Schneider"
                        },
                        new
                        {
                            Id = 74,
                            FirstName = "Anna",
                            IsDeleted = true,
                            LastName = "Keebler"
                        },
                        new
                        {
                            Id = 75,
                            FirstName = "Chester",
                            IsDeleted = true,
                            LastName = "Hamill"
                        },
                        new
                        {
                            Id = 76,
                            FirstName = "Heidi",
                            IsDeleted = true,
                            LastName = "Ankunding"
                        },
                        new
                        {
                            Id = 77,
                            FirstName = "Marjorie",
                            IsDeleted = true,
                            LastName = "Luettgen"
                        },
                        new
                        {
                            Id = 78,
                            FirstName = "Dean",
                            IsDeleted = true,
                            LastName = "Hintz"
                        },
                        new
                        {
                            Id = 79,
                            FirstName = "Jessica",
                            IsDeleted = true,
                            LastName = "McDermott"
                        },
                        new
                        {
                            Id = 80,
                            FirstName = "Samantha",
                            IsDeleted = true,
                            LastName = "Bogisich"
                        },
                        new
                        {
                            Id = 81,
                            FirstName = "Brent",
                            IsDeleted = true,
                            LastName = "Satterfield"
                        },
                        new
                        {
                            Id = 82,
                            FirstName = "Sonya",
                            IsDeleted = false,
                            LastName = "Reichert"
                        },
                        new
                        {
                            Id = 83,
                            FirstName = "Teri",
                            IsDeleted = true,
                            LastName = "Zulauf"
                        },
                        new
                        {
                            Id = 84,
                            FirstName = "Jessie",
                            IsDeleted = true,
                            LastName = "O'Keefe"
                        },
                        new
                        {
                            Id = 85,
                            FirstName = "Monica",
                            IsDeleted = true,
                            LastName = "Abbott"
                        },
                        new
                        {
                            Id = 86,
                            FirstName = "Nick",
                            IsDeleted = true,
                            LastName = "Gorczany"
                        },
                        new
                        {
                            Id = 87,
                            FirstName = "Alvin",
                            IsDeleted = true,
                            LastName = "Jacobs"
                        },
                        new
                        {
                            Id = 88,
                            FirstName = "Dan",
                            IsDeleted = false,
                            LastName = "Strosin"
                        },
                        new
                        {
                            Id = 89,
                            FirstName = "Laura",
                            IsDeleted = true,
                            LastName = "Trantow"
                        },
                        new
                        {
                            Id = 90,
                            FirstName = "Eugene",
                            IsDeleted = false,
                            LastName = "Kunde"
                        },
                        new
                        {
                            Id = 91,
                            FirstName = "Jana",
                            IsDeleted = false,
                            LastName = "Trantow"
                        },
                        new
                        {
                            Id = 92,
                            FirstName = "Joseph",
                            IsDeleted = true,
                            LastName = "Hickle"
                        },
                        new
                        {
                            Id = 93,
                            FirstName = "Elsie",
                            IsDeleted = false,
                            LastName = "Swift"
                        },
                        new
                        {
                            Id = 94,
                            FirstName = "Cedric",
                            IsDeleted = true,
                            LastName = "Cummerata"
                        },
                        new
                        {
                            Id = 95,
                            FirstName = "Tina",
                            IsDeleted = false,
                            LastName = "Lakin"
                        },
                        new
                        {
                            Id = 96,
                            FirstName = "Jeannette",
                            IsDeleted = false,
                            LastName = "Goldner"
                        },
                        new
                        {
                            Id = 97,
                            FirstName = "Clinton",
                            IsDeleted = true,
                            LastName = "McDermott"
                        },
                        new
                        {
                            Id = 98,
                            FirstName = "Felix",
                            IsDeleted = true,
                            LastName = "Jacobs"
                        },
                        new
                        {
                            Id = 99,
                            FirstName = "Willard",
                            IsDeleted = true,
                            LastName = "Dach"
                        },
                        new
                        {
                            Id = 100,
                            FirstName = "Willie",
                            IsDeleted = false,
                            LastName = "Rowe"
                        });
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<int?>("CustomerId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemId");

                    b.Property<int?>("OrderId");

                    b.Property<int>("Quantity");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.Product", b =>
                {
                    b.HasBaseType("Vavatech.EFCore.Models.Item");

                    b.Property<string>("Color");

                    b.Property<float>("Weight");

                    b.HasDiscriminator().HasValue("Product");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.Service", b =>
                {
                    b.HasBaseType("Vavatech.EFCore.Models.Item");

                    b.Property<TimeSpan>("Duration");

                    b.HasDiscriminator().HasValue("Service");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.Order", b =>
                {
                    b.HasOne("Vavatech.EFCore.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.OrderDetail", b =>
                {
                    b.HasOne("Vavatech.EFCore.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("Vavatech.EFCore.Models.Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
