// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vavatech.EFCore.DbServices;

namespace Vavatech.EFCore.DbServices.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20190221123803_AddSalaryToCustomer")]
    partial class AddSalaryToCustomer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vavatech.EFCore.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Pesel");

                    b.Property<decimal>("Salary");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Geraldine",
                            IsDeleted = true,
                            LastName = "Haley",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Myrtle",
                            IsDeleted = true,
                            LastName = "Schmidt",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Katherine",
                            IsDeleted = true,
                            LastName = "Friesen",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Sandra",
                            IsDeleted = false,
                            LastName = "Rice",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Nadine",
                            IsDeleted = true,
                            LastName = "Stroman",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Sally",
                            IsDeleted = true,
                            LastName = "Denesik",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Steven",
                            IsDeleted = true,
                            LastName = "Barrows",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Peggy",
                            IsDeleted = true,
                            LastName = "Bashirian",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Marjorie",
                            IsDeleted = true,
                            LastName = "Gleichner",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Nina",
                            IsDeleted = false,
                            LastName = "Johnson",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Sheldon",
                            IsDeleted = true,
                            LastName = "Torphy",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Drew",
                            IsDeleted = true,
                            LastName = "Aufderhar",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Melinda",
                            IsDeleted = true,
                            LastName = "Trantow",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Marian",
                            IsDeleted = false,
                            LastName = "Green",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Annette",
                            IsDeleted = true,
                            LastName = "Lakin",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Arturo",
                            IsDeleted = true,
                            LastName = "Rodriguez",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Marcos",
                            IsDeleted = true,
                            LastName = "Jerde",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Dean",
                            IsDeleted = true,
                            LastName = "Kirlin",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Charles",
                            IsDeleted = true,
                            LastName = "Schinner",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Roxanne",
                            IsDeleted = true,
                            LastName = "Zieme",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Delbert",
                            IsDeleted = false,
                            LastName = "Konopelski",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Raymond",
                            IsDeleted = false,
                            LastName = "Hintz",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Ellen",
                            IsDeleted = false,
                            LastName = "Rodriguez",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Marie",
                            IsDeleted = false,
                            LastName = "Volkman",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Johnnie",
                            IsDeleted = true,
                            LastName = "Cronin",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Leona",
                            IsDeleted = false,
                            LastName = "Zulauf",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Jermaine",
                            IsDeleted = true,
                            LastName = "Jakubowski",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Steve",
                            IsDeleted = true,
                            LastName = "Goodwin",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Jacqueline",
                            IsDeleted = true,
                            LastName = "Lind",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Antonia",
                            IsDeleted = false,
                            LastName = "Hessel",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "Eric",
                            IsDeleted = true,
                            LastName = "Prosacco",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Darrell",
                            IsDeleted = true,
                            LastName = "McClure",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Willis",
                            IsDeleted = true,
                            LastName = "Jenkins",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Bernard",
                            IsDeleted = true,
                            LastName = "Stokes",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Levi",
                            IsDeleted = true,
                            LastName = "Mayert",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "Mark",
                            IsDeleted = true,
                            LastName = "Greenfelder",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "Peter",
                            IsDeleted = true,
                            LastName = "Hayes",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Joel",
                            IsDeleted = true,
                            LastName = "Gorczany",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Lillie",
                            IsDeleted = true,
                            LastName = "Rowe",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Cameron",
                            IsDeleted = false,
                            LastName = "Cummerata",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "Bernadette",
                            IsDeleted = true,
                            LastName = "Schaden",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "Sheila",
                            IsDeleted = true,
                            LastName = "Rosenbaum",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "Patty",
                            IsDeleted = true,
                            LastName = "Bechtelar",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "Dennis",
                            IsDeleted = true,
                            LastName = "Crist",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "Alberta",
                            IsDeleted = true,
                            LastName = "O'Conner",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "Barry",
                            IsDeleted = true,
                            LastName = "Hirthe",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "Sarah",
                            IsDeleted = true,
                            LastName = "Rohan",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "Gene",
                            IsDeleted = true,
                            LastName = "Grant",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 49,
                            FirstName = "Lloyd",
                            IsDeleted = true,
                            LastName = "Steuber",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 50,
                            FirstName = "Toby",
                            IsDeleted = true,
                            LastName = "Wiza",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 51,
                            FirstName = "Edna",
                            IsDeleted = true,
                            LastName = "Cummerata",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 52,
                            FirstName = "Daryl",
                            IsDeleted = true,
                            LastName = "Hudson",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 53,
                            FirstName = "Cesar",
                            IsDeleted = true,
                            LastName = "Kassulke",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 54,
                            FirstName = "Kirk",
                            IsDeleted = true,
                            LastName = "Beahan",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 55,
                            FirstName = "Wilma",
                            IsDeleted = true,
                            LastName = "Labadie",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 56,
                            FirstName = "Jaime",
                            IsDeleted = true,
                            LastName = "Maggio",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 57,
                            FirstName = "Stephen",
                            IsDeleted = true,
                            LastName = "Lang",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 58,
                            FirstName = "Sandy",
                            IsDeleted = true,
                            LastName = "Toy",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 59,
                            FirstName = "Mary",
                            IsDeleted = true,
                            LastName = "Turcotte",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 60,
                            FirstName = "Marian",
                            IsDeleted = true,
                            LastName = "Hand",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 61,
                            FirstName = "Mandy",
                            IsDeleted = true,
                            LastName = "Abbott",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 62,
                            FirstName = "Melody",
                            IsDeleted = true,
                            LastName = "Daniel",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 63,
                            FirstName = "Angela",
                            IsDeleted = true,
                            LastName = "Jacobi",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 64,
                            FirstName = "Homer",
                            IsDeleted = true,
                            LastName = "Runte",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 65,
                            FirstName = "Gwen",
                            IsDeleted = false,
                            LastName = "Corkery",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 66,
                            FirstName = "Dewey",
                            IsDeleted = false,
                            LastName = "Towne",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 67,
                            FirstName = "Omar",
                            IsDeleted = true,
                            LastName = "Von",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 68,
                            FirstName = "Eula",
                            IsDeleted = true,
                            LastName = "Paucek",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 69,
                            FirstName = "Angel",
                            IsDeleted = true,
                            LastName = "Lesch",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 70,
                            FirstName = "Luz",
                            IsDeleted = true,
                            LastName = "Mueller",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 71,
                            FirstName = "Mack",
                            IsDeleted = true,
                            LastName = "Christiansen",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 72,
                            FirstName = "Allan",
                            IsDeleted = true,
                            LastName = "Conroy",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 73,
                            FirstName = "Deborah",
                            IsDeleted = true,
                            LastName = "Cormier",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 74,
                            FirstName = "Christie",
                            IsDeleted = true,
                            LastName = "Ward",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 75,
                            FirstName = "Erick",
                            IsDeleted = true,
                            LastName = "Auer",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 76,
                            FirstName = "Olga",
                            IsDeleted = true,
                            LastName = "Bechtelar",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 77,
                            FirstName = "Josefina",
                            IsDeleted = false,
                            LastName = "Jerde",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 78,
                            FirstName = "Marion",
                            IsDeleted = false,
                            LastName = "Rippin",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 79,
                            FirstName = "Tonya",
                            IsDeleted = true,
                            LastName = "Collier",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 80,
                            FirstName = "Audrey",
                            IsDeleted = true,
                            LastName = "Steuber",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 81,
                            FirstName = "Vanessa",
                            IsDeleted = false,
                            LastName = "Haag",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 82,
                            FirstName = "Reginald",
                            IsDeleted = true,
                            LastName = "Kovacek",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 83,
                            FirstName = "Neil",
                            IsDeleted = true,
                            LastName = "Fahey",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 84,
                            FirstName = "Tamara",
                            IsDeleted = true,
                            LastName = "Weber",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 85,
                            FirstName = "Ollie",
                            IsDeleted = true,
                            LastName = "O'Kon",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 86,
                            FirstName = "Trevor",
                            IsDeleted = true,
                            LastName = "Lindgren",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 87,
                            FirstName = "Clark",
                            IsDeleted = false,
                            LastName = "Hammes",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 88,
                            FirstName = "Shannon",
                            IsDeleted = true,
                            LastName = "Wintheiser",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 89,
                            FirstName = "Myra",
                            IsDeleted = true,
                            LastName = "Torphy",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 90,
                            FirstName = "Elisa",
                            IsDeleted = true,
                            LastName = "Nader",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 91,
                            FirstName = "Wanda",
                            IsDeleted = true,
                            LastName = "Rodriguez",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 92,
                            FirstName = "Gerald",
                            IsDeleted = false,
                            LastName = "Schiller",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 93,
                            FirstName = "Salvador",
                            IsDeleted = false,
                            LastName = "Bartell",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 94,
                            FirstName = "Rosemary",
                            IsDeleted = true,
                            LastName = "Pollich",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 95,
                            FirstName = "Billie",
                            IsDeleted = false,
                            LastName = "VonRueden",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 96,
                            FirstName = "Vickie",
                            IsDeleted = true,
                            LastName = "Hettinger",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 97,
                            FirstName = "Penny",
                            IsDeleted = true,
                            LastName = "Effertz",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 98,
                            FirstName = "Elaine",
                            IsDeleted = false,
                            LastName = "Harber",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 99,
                            FirstName = "Luis",
                            IsDeleted = true,
                            LastName = "Welch",
                            Salary = 0m
                        },
                        new
                        {
                            Id = 100,
                            FirstName = "Terrance",
                            IsDeleted = true,
                            LastName = "Johnson",
                            Salary = 0m
                        });
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<int?>("CustomerId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemId");

                    b.Property<int?>("OrderId");

                    b.Property<int>("Quantity");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.Product", b =>
                {
                    b.HasBaseType("Vavatech.EFCore.Models.Item");

                    b.Property<string>("Color");

                    b.Property<float>("Weight");

                    b.HasDiscriminator().HasValue("Product");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.Service", b =>
                {
                    b.HasBaseType("Vavatech.EFCore.Models.Item");

                    b.Property<TimeSpan>("Duration");

                    b.HasDiscriminator().HasValue("Service");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.Order", b =>
                {
                    b.HasOne("Vavatech.EFCore.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.OrderDetail", b =>
                {
                    b.HasOne("Vavatech.EFCore.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("Vavatech.EFCore.Models.Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
