// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vavatech.EFCore.DbServices;

namespace Vavatech.EFCore.DbServices.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20190221110158_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vavatech.EFCore.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Betsy",
                            IsDeleted = true,
                            LastName = "Batz"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Dianne",
                            IsDeleted = true,
                            LastName = "Kihn"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Nathaniel",
                            IsDeleted = true,
                            LastName = "Parker"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Sally",
                            IsDeleted = false,
                            LastName = "Bode"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Delores",
                            IsDeleted = true,
                            LastName = "Kertzmann"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Donna",
                            IsDeleted = true,
                            LastName = "Kuvalis"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Erick",
                            IsDeleted = true,
                            LastName = "Prosacco"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Jana",
                            IsDeleted = true,
                            LastName = "Mertz"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Nathan",
                            IsDeleted = false,
                            LastName = "Wisozk"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Moses",
                            IsDeleted = true,
                            LastName = "Jast"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Bethany",
                            IsDeleted = false,
                            LastName = "Goyette"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Larry",
                            IsDeleted = false,
                            LastName = "Purdy"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Ruben",
                            IsDeleted = true,
                            LastName = "Herzog"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Alton",
                            IsDeleted = true,
                            LastName = "Fahey"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Victor",
                            IsDeleted = true,
                            LastName = "Reichel"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Jamie",
                            IsDeleted = true,
                            LastName = "Zemlak"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Bryant",
                            IsDeleted = true,
                            LastName = "Nienow"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Sonja",
                            IsDeleted = false,
                            LastName = "Huel"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Stephanie",
                            IsDeleted = false,
                            LastName = "Blanda"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Penny",
                            IsDeleted = true,
                            LastName = "Von"
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Agnes",
                            IsDeleted = true,
                            LastName = "Gottlieb"
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Erma",
                            IsDeleted = true,
                            LastName = "Moen"
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Dwight",
                            IsDeleted = true,
                            LastName = "Donnelly"
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Bryan",
                            IsDeleted = false,
                            LastName = "Jaskolski"
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Lowell",
                            IsDeleted = true,
                            LastName = "Bernhard"
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Neal",
                            IsDeleted = false,
                            LastName = "Bednar"
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Jason",
                            IsDeleted = true,
                            LastName = "Deckow"
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Dustin",
                            IsDeleted = true,
                            LastName = "Ward"
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Eugene",
                            IsDeleted = true,
                            LastName = "O'Connell"
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Jamie",
                            IsDeleted = true,
                            LastName = "Simonis"
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "Rex",
                            IsDeleted = true,
                            LastName = "Haag"
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Penny",
                            IsDeleted = true,
                            LastName = "Lakin"
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Lena",
                            IsDeleted = true,
                            LastName = "Mann"
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Eric",
                            IsDeleted = true,
                            LastName = "Schultz"
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Luther",
                            IsDeleted = true,
                            LastName = "Satterfield"
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "Shaun",
                            IsDeleted = true,
                            LastName = "Purdy"
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "Brenda",
                            IsDeleted = true,
                            LastName = "Russel"
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Jackie",
                            IsDeleted = true,
                            LastName = "Kuhic"
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Rolando",
                            IsDeleted = true,
                            LastName = "Steuber"
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Paul",
                            IsDeleted = true,
                            LastName = "Hansen"
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "William",
                            IsDeleted = true,
                            LastName = "Kutch"
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "Doreen",
                            IsDeleted = true,
                            LastName = "Bogisich"
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "Ana",
                            IsDeleted = true,
                            LastName = "Leffler"
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "Benjamin",
                            IsDeleted = false,
                            LastName = "Cartwright"
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "Emmett",
                            IsDeleted = true,
                            LastName = "Thiel"
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "Tommy",
                            IsDeleted = false,
                            LastName = "Bednar"
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "Marianne",
                            IsDeleted = true,
                            LastName = "Considine"
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "Hector",
                            IsDeleted = true,
                            LastName = "Johnston"
                        },
                        new
                        {
                            Id = 49,
                            FirstName = "Sam",
                            IsDeleted = false,
                            LastName = "Braun"
                        },
                        new
                        {
                            Id = 50,
                            FirstName = "Beatrice",
                            IsDeleted = true,
                            LastName = "Zulauf"
                        },
                        new
                        {
                            Id = 51,
                            FirstName = "Corey",
                            IsDeleted = true,
                            LastName = "Hartmann"
                        },
                        new
                        {
                            Id = 52,
                            FirstName = "Shane",
                            IsDeleted = true,
                            LastName = "Greenfelder"
                        },
                        new
                        {
                            Id = 53,
                            FirstName = "Daryl",
                            IsDeleted = true,
                            LastName = "Buckridge"
                        },
                        new
                        {
                            Id = 54,
                            FirstName = "Pamela",
                            IsDeleted = false,
                            LastName = "Langosh"
                        },
                        new
                        {
                            Id = 55,
                            FirstName = "George",
                            IsDeleted = true,
                            LastName = "Klocko"
                        },
                        new
                        {
                            Id = 56,
                            FirstName = "Dixie",
                            IsDeleted = true,
                            LastName = "Spencer"
                        },
                        new
                        {
                            Id = 57,
                            FirstName = "Daryl",
                            IsDeleted = true,
                            LastName = "Mohr"
                        },
                        new
                        {
                            Id = 58,
                            FirstName = "Ruth",
                            IsDeleted = false,
                            LastName = "Brakus"
                        },
                        new
                        {
                            Id = 59,
                            FirstName = "Elsa",
                            IsDeleted = true,
                            LastName = "Heaney"
                        },
                        new
                        {
                            Id = 60,
                            FirstName = "Mike",
                            IsDeleted = true,
                            LastName = "Haley"
                        },
                        new
                        {
                            Id = 61,
                            FirstName = "Kathleen",
                            IsDeleted = true,
                            LastName = "Kilback"
                        },
                        new
                        {
                            Id = 62,
                            FirstName = "Marcella",
                            IsDeleted = false,
                            LastName = "Smitham"
                        },
                        new
                        {
                            Id = 63,
                            FirstName = "Bill",
                            IsDeleted = true,
                            LastName = "Jacobi"
                        },
                        new
                        {
                            Id = 64,
                            FirstName = "Lewis",
                            IsDeleted = false,
                            LastName = "Marvin"
                        },
                        new
                        {
                            Id = 65,
                            FirstName = "Edgar",
                            IsDeleted = true,
                            LastName = "Buckridge"
                        },
                        new
                        {
                            Id = 66,
                            FirstName = "Kelley",
                            IsDeleted = false,
                            LastName = "Bogisich"
                        },
                        new
                        {
                            Id = 67,
                            FirstName = "Mathew",
                            IsDeleted = false,
                            LastName = "Kunze"
                        },
                        new
                        {
                            Id = 68,
                            FirstName = "Alton",
                            IsDeleted = true,
                            LastName = "Smitham"
                        },
                        new
                        {
                            Id = 69,
                            FirstName = "May",
                            IsDeleted = true,
                            LastName = "Hoppe"
                        },
                        new
                        {
                            Id = 70,
                            FirstName = "Alex",
                            IsDeleted = true,
                            LastName = "Gerhold"
                        },
                        new
                        {
                            Id = 71,
                            FirstName = "Derrick",
                            IsDeleted = true,
                            LastName = "Moen"
                        },
                        new
                        {
                            Id = 72,
                            FirstName = "Shannon",
                            IsDeleted = true,
                            LastName = "Blick"
                        },
                        new
                        {
                            Id = 73,
                            FirstName = "Sharon",
                            IsDeleted = false,
                            LastName = "Ullrich"
                        },
                        new
                        {
                            Id = 74,
                            FirstName = "Dwayne",
                            IsDeleted = true,
                            LastName = "Rippin"
                        },
                        new
                        {
                            Id = 75,
                            FirstName = "Lila",
                            IsDeleted = true,
                            LastName = "Daniel"
                        },
                        new
                        {
                            Id = 76,
                            FirstName = "Katie",
                            IsDeleted = true,
                            LastName = "Auer"
                        },
                        new
                        {
                            Id = 77,
                            FirstName = "Alfredo",
                            IsDeleted = false,
                            LastName = "Jaskolski"
                        },
                        new
                        {
                            Id = 78,
                            FirstName = "Rene",
                            IsDeleted = true,
                            LastName = "Heidenreich"
                        },
                        new
                        {
                            Id = 79,
                            FirstName = "Sonja",
                            IsDeleted = true,
                            LastName = "Paucek"
                        },
                        new
                        {
                            Id = 80,
                            FirstName = "Ross",
                            IsDeleted = true,
                            LastName = "Watsica"
                        },
                        new
                        {
                            Id = 81,
                            FirstName = "Lora",
                            IsDeleted = true,
                            LastName = "Corwin"
                        },
                        new
                        {
                            Id = 82,
                            FirstName = "Naomi",
                            IsDeleted = false,
                            LastName = "Kuhn"
                        },
                        new
                        {
                            Id = 83,
                            FirstName = "Kristi",
                            IsDeleted = true,
                            LastName = "White"
                        },
                        new
                        {
                            Id = 84,
                            FirstName = "Guillermo",
                            IsDeleted = false,
                            LastName = "Ruecker"
                        },
                        new
                        {
                            Id = 85,
                            FirstName = "Devin",
                            IsDeleted = true,
                            LastName = "Schmidt"
                        },
                        new
                        {
                            Id = 86,
                            FirstName = "Sandra",
                            IsDeleted = true,
                            LastName = "Von"
                        },
                        new
                        {
                            Id = 87,
                            FirstName = "Rudolph",
                            IsDeleted = true,
                            LastName = "Kuvalis"
                        },
                        new
                        {
                            Id = 88,
                            FirstName = "Alma",
                            IsDeleted = true,
                            LastName = "Metz"
                        },
                        new
                        {
                            Id = 89,
                            FirstName = "Jack",
                            IsDeleted = true,
                            LastName = "Donnelly"
                        },
                        new
                        {
                            Id = 90,
                            FirstName = "Fannie",
                            IsDeleted = true,
                            LastName = "Stiedemann"
                        },
                        new
                        {
                            Id = 91,
                            FirstName = "Lindsay",
                            IsDeleted = true,
                            LastName = "Lemke"
                        },
                        new
                        {
                            Id = 92,
                            FirstName = "Preston",
                            IsDeleted = true,
                            LastName = "Murazik"
                        },
                        new
                        {
                            Id = 93,
                            FirstName = "Elena",
                            IsDeleted = true,
                            LastName = "Trantow"
                        },
                        new
                        {
                            Id = 94,
                            FirstName = "Kerry",
                            IsDeleted = true,
                            LastName = "Littel"
                        },
                        new
                        {
                            Id = 95,
                            FirstName = "Jacquelyn",
                            IsDeleted = true,
                            LastName = "Kiehn"
                        },
                        new
                        {
                            Id = 96,
                            FirstName = "Leland",
                            IsDeleted = true,
                            LastName = "Schuppe"
                        },
                        new
                        {
                            Id = 97,
                            FirstName = "Sonya",
                            IsDeleted = true,
                            LastName = "Abshire"
                        },
                        new
                        {
                            Id = 98,
                            FirstName = "Marie",
                            IsDeleted = false,
                            LastName = "Lindgren"
                        },
                        new
                        {
                            Id = 99,
                            FirstName = "Dolores",
                            IsDeleted = true,
                            LastName = "Volkman"
                        },
                        new
                        {
                            Id = 100,
                            FirstName = "Patsy",
                            IsDeleted = true,
                            LastName = "Hettinger"
                        });
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<int?>("CustomerId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemId");

                    b.Property<int?>("OrderId");

                    b.Property<int>("Quantity");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.Product", b =>
                {
                    b.HasBaseType("Vavatech.EFCore.Models.Item");

                    b.Property<string>("Color");

                    b.Property<float>("Weight");

                    b.HasDiscriminator().HasValue("Product");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.Service", b =>
                {
                    b.HasBaseType("Vavatech.EFCore.Models.Item");

                    b.Property<TimeSpan>("Duration");

                    b.HasDiscriminator().HasValue("Service");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.Order", b =>
                {
                    b.HasOne("Vavatech.EFCore.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("Vavatech.EFCore.Models.OrderDetail", b =>
                {
                    b.HasOne("Vavatech.EFCore.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("Vavatech.EFCore.Models.Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
